src/main/java/com/eprosima/fastrtps/idl/templates/RTPSPublisherSource.stg

This PR removes dependencies from eClock, making use of C++11 capabilities.

Refs #6311 Remove eClock dependencies. [6320]

---

src/test/java/com/eprosima/fastrtps/FastRTPSGenTest.java

* Added parallel build
* Check if Fast-RTPS was already built

Speedup testing [6501]

---

src/main/java/com/eprosima/fastrtps/fastrtpsgen.java
src/main/java/com/eprosima/fastrtps/idl/templates/Common.stg

With this PR few declarations of function for union types are not generated, because their definitions were never generated.

Fixed generation of not defined functions. [7446]

---

.gitignore
src/main/java/com/eprosima/fastcdr/idl/context/Context.java
src/main/java/com/eprosima/fastrtps/fastrtpsgen.java
src/main/java/com/eprosima/fastrtps/idl/grammar/Context.java
src/main/java/com/eprosima/fastrtps/idl/templates/RTPSPubSubTypeSource.stg

Fixes https://github.com/eProsima/Fast-RTPS-Gen/issues/19. @LuisGP thank you for the tips. Please check if this solution makes sense to you:
1.  `-typeros2` option sets `m_type_ros2` to `true`, which is defined in the Context;
1.  If `isGenerateTypesROS2` is true,  meaning `m_type_ros2`, then it's used a scoped name generated from the IDL parser, which has the required valid structure to be used in the ROS2 context.
Requires https://github.com/eProsima/IDL-Parser/pull/39 to be merged first.

Feature: generate ROS2 compatible type naming

---

src/main/java/com/eprosima/fastrtps/idl/grammar/Context.java

Building in Gradle 6.2, I was seeing the following warning:
```sh
> Task :compileJava
/home/nuno/Fast-RTPS-Gen/src/main/java/com/eprosima/fastrtps/idl/grammar/Context.java:190: warning: [unchecked] unchecked call to SimpleEntry(K,V) as a member of the raw type SimpleEntry
typecodes.add(new SimpleEntry(sequence.getCppTypename(), sequence));
^
where K,V are type-variables:
K extends Object declared in class SimpleEntry
V extends Object declared in class SimpleEntry
/home/nuno/Fast-RTPS-Gen/src/main/java/com/eprosima/fastrtps/idl/grammar/Context.java:190: warning: [unchecked] unchecked method invocation: method add in class ArrayList is applied to given types
typecodes.add(new SimpleEntry(sequence.getCppTypename(), sequence));
^
required: E
found: SimpleEntry
where E is a type-variable:
E …
```

Context: fix warning on unchecked method invocation for AbstractMap.SimpleEntry<String, TypeCode>

---

build.gradle
src/test/java/com/eprosima/fastrtps/FastRTPSGenTest.java

Fixes https://github.com/eProsima/Fast-RTPS-Gen/issues/26 by:
1. Bumping the testing platform to JUnit 5 (not mandatory but might be reasonable);
2. Fixing `fastrtpsgen.jar` path in `FastRTPSGenTest.java`.
@LuisGP @richiprosima FYI review and acceptance.

Gradle: fix test stage

---

build.gradle

Adds install step that copies the `fastrtpsgen` script and `fastrtpsgen.jar` into `/usr/local`. I didn't make this OS agnostic, but I would suppose that most of the use cases for this are Linux/Unix based systems. I guess this will be good as a start.
@LuisGP @richiprosima @MiguelCompany

Gradle: add install step

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberSource.stg

This PR makes the subscriber example code check for `valid_data` instead of `instance_state == ALIVE`.
This way, the example code follows the way suggested by the DDS standard.

Use valid_data instead of instance_state [10078]

---

src/main/java/com/eprosima/fastdds/idl/templates/Common.stg

This should fix #60 by using `member.annotationKey`, which already checks both for `@key` and `@Key` annotations.

Use member.annotationKey instead of annotations map [11597]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSwigInterface.stg
src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg

This pull request adds support to generate Python binding files for the generated data types.
- Adds a new option '-python' that enables the generation of python binding files
- Each IDL file will result in a new python module that will contain all the data types defined in that IDL
- Creates a CMake file that enables the compilation and the generation of the binding using SWIG
- Only simple Structs with basic types are supported (no nested structs, no arrays or maps)

Basic Python bindings [12206]

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg

When defining a map in the IDL, only primitive keys were allowed. This PR implements the correct behavior.
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

[12537] Fix map type

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypeObjectHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypeObjectSource.stg

When types are located inside a module (namespace), the source code generated is wrong. This PR fixes this.
Depends on eProsima/IDL-Parser#48

Fix typeobject generation when using modules [12672]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg

**IMPORTANT:** Merge after #75 
The only relevant changes are on the last commit (0ceb2d9), the rest is part of PR #75 
Adds comparison operators `operator==()` and `operator!=()` to the generated classes.

comparison operators [12880]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg

Prevents a _control reaches end of non-void function_ warning for Union equality comparisons.
Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>

Added return statement to Union comparison operator

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypeObjectHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationHeader.stg

Added _FAST_DDS_GENERATED_ to prevent guards overlapping for some common types and words.
Added const keyword to equality and non-equality operators

[13333] Modified Compilation guards and comparison operator generation

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg

This PR makes the generated `<>PubSubType::deserialize` safer by catching the `NotEnoughMemoryException` that `Cdr::read_encapsulation()` may throw
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>

Make <>PubSubType::deserialize safer [13941]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypeObjectSource.stg

This fixes a bug on the generation of the TypeObject registration code, when there are arrays / sequences of `long double`.

[13987] Use cppTypenameForTypeId to generate `get_xxx_identifier`

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

This PR changes the generated code for bounded strings, so `eprosima::fastrtps::fixed_string<N>` is used instead of `std::string`
Depends on eProsima/IDL-Parser#53

[14671] Fix generated code for bounded strings

---

src/main/java/com/eprosima/fastdds/idl/grammar/Context.java

Prefer pure ASCII, avoid UTF8 in sources. Fixes #53.
Signed-off-by: Nicolas Benes <nbenes.gh@xandea.de>

[14912] Remove non-ASCII character from source

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg

This squelches -Winconsistent-missing-destructor-override when building with clang

[14913] Override generated destructors

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

Since:
1. OMG IDL to C++ mapping of structured types does not require it
2. We want plain types to be plain (i.e. have nothing more in memory than plain data)
This PR makes the destructors of the generated data types non virtual.

[15612] Make generated destructors non virtual

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/VS.stg
src/main/java/com/eprosima/fastdds/util/VSConfiguration.java

Align visual studio generators with current windows installer of Fast DDS
1. Generate solutions for VS 2019
2. Fixed the static libraries linked

[15824] Cleanup visual studio example generators

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg

According to clang-tidy:
> Move constructors of all the types used with STL containers, for example, need to be declared noexcept. Otherwise STL will choose copy constructors instead. The same is valid for move assignment operations.
https://clang.llvm.org/extra/clang-tidy/checks/performance/noexcept-move-constructor.html
(Partially) fixes #58

Add noexcept to generated move constructors/assignments

---

gradle/wrapper/gradle-wrapper.properties

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
Fixes #146. `gradlew` script downloads Gradle 7.0. Support for Java 17 was introduced in Gradle 7.3. This PR updates Gradle version in `gradlew`script to Gradle 7.6.

[16655] Update gradlew version

---

build.gradle
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/AliasTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/ArrayTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/BitmaskTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/BitsetTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/EnumTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/MapTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/PrimitiveTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/SequenceTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/SetTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/StringTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/StructTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/TypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/UnionTypeCode.java
src/main/java/com/eprosima/fastdds/idl/templates/Common.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/eprosima.stg
src/main/java/com/eprosima/fastdds/idl/templates/idlTypes.stg
src/test/java/com/eprosima/fastdds/FastDDSGenTest.java

According to OMG IDL standard, recursive structures are supported using `sequences` and forward declarations. This PR
add support for this and also:
- Improve test execution
- Fix bug generating bitset and bitmask
Depends on:
- eProsima/IDL-Parser#57
- #129

Support for generating recursive structures [15347]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

When handling the bitmask bit shifts, the `0x01` literal is treated as a signed integer producing, making the resulting value a negative when shifting the whole size of the datatype.
This PR forces the usage of an `unsigned long long` integer instead.

[17336] Forced unsigned usage on assignment

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg

This calculation is only done when fastddsgen thinks the structure is plain. This feature adds a runtime check to avoid errors.
Depends on:
- eProsima/idl-parser#71

Runtime calculation about if a type is plain [18162]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg

This PR fixes python generated code with nested sequences like:
```
struct Test{
sequence<sequence<double> >  data;
};
```
Fixes #157 .

Fix nested sequences [17650]

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg

Next idl
```idl
struct EmptyDerived : Basic
{
};
```
generates a wrong `operator==`. This PR fixes it.
Depends on:
- eprosima/idl-parser#67

Fix generation of an empty struct [17527]

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg

This bug was introduced by #169.
More info in redmine 18520.

Fix error when swig read a generated header file [18521]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg

This PR avoids generating the get_buffer function for python SWIG templates when the type is a sequence of booleans

[18819] Do not generate get_buffer for bool vector

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypeObjectSource.stg

This PR adds name mangling to type object registration code when using `-typeros2` flag

[18910] Correctly register type object with ROS 2 names

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg
src/main/java/com/eprosima/fastdds/solution/Project.java
src/main/java/com/eprosima/fastdds/util/Utils.java
src/test/java/com/eprosima/fastdds/FastDDSGenTest.java

Depends on:
- eProsima/IDL-Parser#76
For a case where an IDL file includes another one in another directory, the generation fails.
```idl
#include "helper/other.idl"
...
```

Fix generating code when the dependency is in another directory

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg

PR #156 added the inclusion of `PubSubTypes.h` headers of dependant IDL files in the current generated `PubSubTypes.h`. But these files not always are generated if there are no structures in the IDL file. This causes a compilation error.
This PR fixes this always creating the `PubSubTypes.h` files.

Fix including an IDL file with no structures [19387]

---

src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg

The code generated is now designed for Fast CDR >= 2.0 and Fast DDS >= 2.12, so the generated CMakeLists.txt should require those versions.

Require minimum versions on CMakeLists template.

---

build.gradle
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg

[19236] Fix bitmask code generation

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
src/main/java/com/eprosima/fastdds/idl/parser/typecode/ArrayTypeCode.java
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg

Also this PR fix warning with arrays' initial value and fix the end of two files.

Maintain xtypes serialization to previous encoding version to maintain interop [19624]

---

src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectHeader.stg

#244 included non-necessary templates into Fast DDS-Gen. It was not detected because current test suite does not run TypeObject generation code. This PR fixes the issue.

[19784] Remove code from TypeObjectHeader.stg

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
src/main/java/com/eprosima/fastdds/idl/parser/typecode/StructTypeCode.java
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg

* eProsima/IDL-Parser#99
XTypes v1.3 Clause 7.2.2.4.5
> The Type System supports single inheritance of Aggegated [sic] Types.
IDL v1.4 Clause 7.4.13.4
> Additions to structure definition in order to support single inheritance and void content (no members).

[19792] Remove multiple inheritance

---

.github/dco.yml
.github/workflows/mirror.yml

This PR adds a mirror workflow so that the latest version branch is kept up to date with master.
This is necessary to transition to a branching model similar to Fast DDS', where master is kept as a development branch, and each minor version has a corresponding X.Y.x branch so we can handle backports and releases in a more consistent manner.

[19898] Add mirror workflow

---

resources/Custom.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/eprosima.stg
src/test/java/com/eprosima/fastdds/FastDDSGenTest.java

Branch created for merging typeobjects and their tests.
Needs: https://github.com/eProsima/IDL-Parser/pull/103

[19595] Typeobjects with tests

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg

Depends on:
- eprosima/idl-parser#111

Add argument to change default unbounded countainer max size [20066]

---

src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg

This PR fixes warnings in:
* eProsima/Fast-DDS#3996
Before merging, let's see if no more warnings appear.
This PR also updates the DDS Types Test submodule to the latest main commit.

[19837] Fix CLang warning in generated code about unused lambda capture

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java

Make fastddsgen add “eprosima” and “fastdds” when “dds” modules are found in IDLs.
Add a -no-dependencies option to avoid generating files for dependencies.

[#20097] Add replacement for "dds" modules and -no-dependencies option to fastddsgen

---

src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg
src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg

Reduce CMake minimum version required for Fast DDS compatibility against RHEL 9.

[20176] Downgrade cmake version

---

src/main/java/com/eprosima/fastdds/fastddsgen.java

This PR adds a new flag `-flat-output-dir` (the name can be discussed) so that relative paths from the input `idl` files can be ignored and the generated files placed either in the default or `-d` directory.

[20235] Add flat-output-dir flag to ignore inputs relative paths

---

src/main/java/com/eprosima/fastdds/fastddsgen.java

This PR adds the missing documentation for the `flat-otuput-dir` https://github.com/eProsima/Fast-DDS-Gen/pull/287

[20235] flat-output-dir option help

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeaderv1.stg

This PR adds the `#include <cstdint>` header for `v1` generated types and sorts the includes in ascending order. This is a consequence of a compilation [issue](https://github.com/eProsima/Fast-DDS/pull/4337) that was detected when compiling with `gcc 13.2.0` (ubuntu 24.04)

[20272] Add cstdint header in v1 generated types

---

src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

This PR includes updates to the tests for indirect hash TypeIdentifiers. Now, maps consider the key when determining equiv_kind.
It updates the union tests to accommodate the member_id change. See more details at https://github.com/eProsima/IDL-Parser/pull/123.

20538 Update FastDDSGen tests for indirect hashes

---

src/main/java/com/eprosima/fastdds/idl/parser/typecode/AliasTypeCode.java
src/main/java/com/eprosima/fastdds/idl/parser/typecode/StructTypeCode.java

This PR fixes an inheritance from an alias is not generated.
Depends on:
- eprosima/idl-parser#125

Fix inheritance with aliases [20621]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg

This PR accounts for changes in:
* eprosima/fast-dds#4500

[20569] Migrate DLL API exporter to fastdds

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeaderv1.stg
src/main/java/com/eprosima/fastdds/idl/parser/typecode/StringTypeCode.java
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg

This PR updates fastrtps migrated headers:
`fixed_size_string.hpp` 
`md5.h` 
`SerializedPayload.h`
Related PR:
* https://github.com/eProsima/Fast-DDS/pull/4518

[20566] Update fastrtps migrated headers 

---

build.gradle

This PR:
1. Upgrades IDL-Parser to v1.6.1
2. Bumps the project version to 2.5.2

[20741] Bump version to 2.5.2

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg

Depends on:
- eprosima/idl-parser#138

Fix windows warning with an union with boolean discriminator [20975]

---

src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

Fixes warnings on Visual Studio 2013 introduced in TypeObject generated code.
Depends on:
- eprosima/idl-parser#140

Fix windows warning in TypeObject generated source code [21006]

---

.github/workflows/mirror.yml

This PR adds a mirror workflow to 2.5.x so that 2.5.x is mirrored in 2.x

[20893] Add mirror job

---

src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

* eProsima/IDL-Parser#135
* eProsima/Fast-DDS#4746
This PR improves:
* TypeObject registry API returning the registered TypeIdentifier.
* TypeObject test suite, registering only the tested structure/union to ensure registration consistency.

[20853] Improve TypeObject registry API

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/parser/typecode/BitsetTypeCode.java
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

Generate bitsets according to standard IDL to C++11 2021.
Depends on:
- #332 
- eprosima/idl-parser#145

Bitsets according to standard IDL to C++11 2021 [21028]

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg

This PR changes the behaviour how generated python packages are installed, more Python style

Installing python modules correctly [21071]

---

.github/workflows/reusable-ubuntu-ci.yaml

This PR uses a token for the setup-ccache action from in the CI, which is behind the CI failures on post steps due to exceeding github API usage rate limits
@Mergifyio backport 3.3.x 3.2.x 2.5.x 2.1.x

[21168] Use token for ccache action

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

With this refactor, any registration in TypeObjectRegistry will return a TypeIdentifierPair which a TopicDataType can use to configure internally DDS.

TypeObjectRegistry refactor [21148]

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/JNISource.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg

This PR migrates fastrtps namespace to fastdds.
Related Fast DDS PR:
* https://github.com/eProsima/Fast-DDS/pull/4898
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 

[21129] Migrate fastrtps namespace to fastdds

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

An IDL enumeration will be translated to a C++ signed integer enumeration.
```c++
enum class MyEnum : int32_t
{
}
```
- Related documentation PR: eProsima/Fast-DDS-docs#821

Enumerations are traslated to C++ signed integer enumeration [21200]

---

.github/actions/fetch-fastddsgen-repos/action.yml
.github/workflows/reusable-ubuntu-ci.yaml
.github/workflows/ubuntu-ci.yaml
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/JNISource.stg

This PR adjusts Fast DDS Gen for:
* eProsima/Fast-DDS#4960

[21183] Adjust for `const` qualification of all data related inputs in DataWriter APIs

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubMain.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSwigInterface.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/JNISource.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectHeader.stg

This PR is the FastDDS Gen counterpart of this FastDDS PR:
- #eProsima/Fast-DDS/pull/4958
This is part of the set of PRs preparing the new major version 3.x in FastDDS. Consequently, it cannot be backported

[21128] Update guards and extenstion .h to .hpp in headers

---

src/main/java/com/eprosima/fastdds/idl/grammar/Context.java

This PR only update the IDL parser submodule to the one which fixes this.
Depends on:
- eprosima/idl-parser#149

Fix default enclosing type for 1-byte bitfield [21265]

---

src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg

Due to an error, fastdds_python doesn't compile with current SWIG version (4.2.0) on Ubuntu 24.04. The fix is in swig 4.2.1 but it's not accessible in ubuntu noble. This ubuntu also contains the package swig4.1 but CMake is not prepare to find its executable. This PR fixes this using a trick.
Related to:
- eprosima/fast-dds-python#153

[21277] Support compilation against Ubuntu 24.04 swig4.1

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

This PR adds support for union discriminator's `@default` annotation.
Depends on:
- eprosima/dds-types-test#32
- eprosima/idl-parser#148

Support union discriminator's @default annotation

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/DDSApplicationHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSApplicationSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubMain.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberSource.stg

The Fast DDS examples have been refactored, making them homogeneous and more self-explained, with an improved README markdown file and best practices usage.
This PR introduces the same structure in the Fast DDS Gen generated examples.
Tested locally

[21324] Adapt example generation to Fast DDS examples refactor

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSwigInterface.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg

Implementation of XCDR introduces new functions in `TopicDataType` class. But the old one remained. This PR removes them before launching the major version 3, and also performs additional refactorings:
- Change method names to `snake_case` and have more meaningful names.
- Change arguments from pointer to reference where applicable
- Use `std::string` instead of `char*` on name getters and setters

[21351] Refactor `TopicDataType`

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg

The upcoming Fast DDS Gen v4.0.0 will generated code for Fast DDS v3.0, which requieres Fast CDR v2. For this reason, this PR removes all the compiled conditioned generated code relative to Fast CDR v1. This PR is the counterpart of:
* eProsima/Fast-DDS#5073
Depends on: 
* #375

[21325] Remove all code related to FAST CDR v1

---

src/main/java/com/eprosima/fastdds/fastddsgen.java

This PR includes some minor fixes and removes the old **-typeobject** argument from the help description of Fast-DDS-Gen.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports have been included in the description.
- _N/A_: Check CI results: changes do not issue any warning.
- _N/A_: Check CI results: failing tests are unrelated with the changes.

[20362] Changes for xtypes1.3 doc

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg

This PR refactors the key hash calculation as DDS-XTypes 1.3 specifies.
Depends on:
- eprosima/dds-types-test#35
- eprosima/idl-parser#153
- eprosima/idl-parser#154

[21392] Refactor key hash calculation according to DDS X-Types 1.3

---

README.md
build.gradle

This PR bumps to Fast DDS gen v4.0.0
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 

[21366] Bump to v4.0.0

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

Use FINAL extensibility for ROS2 types by default.
Depends on:
- eprosima/idl-parser#157

[21605] Use @FINAL for ROS2 types by default

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

This PR fixes next warning:
```
constantsPubSubTypes.cxx
D:\a\Fast-DDS\Fast-DDS\src\fastdds\test\dds-types-test\constants.hpp(60,31): error C2220: the following warning is treated as an error (compiling source file D:\a\Fast-DDS\Fast-DDS\src\fastdds\test\dds-types-test\constantsPubSubTypes.cxx) [D:\a\Fast-DDS\Fast-DDS\build\fastdds\test\dds\xtypes\DDSXtypesCommunication.vcxproj]
[Processing: fastdds]
D:\a\Fast-DDS\Fast-DDS\src\fastdds\test\dds-types-test\constants.hpp(60,31): warning C4305: 'initializing': truncation from 'double' to 'float' (compiling source file D:\a\Fast-DDS\Fast-DDS\src\fastdds\test\dds-types-test\constantsPubSubTypes.cxx) [D:\a\Fast-DDS\Fast-DDS\build\fastdds\test\dds\xtypes\DDSXtypesCommunication.vcxproj]
constantsTypeObjectSupport.cxx
declarationsPubSubTypes.cxx …
```

[21625] Fix warning on Windows

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

Fix compilation warning in Ubuntu 24.04 with `-Werror`. The error is:
```
[ 32%] Building CXX object src/cpp/CMakeFiles/fastdds.dir/fastdds/xtypes/type_representation/TypeObjectUtils.cpp.o 
In file included from /home/runner/work/Fast-DDS-docs/Fast-DDS-docs/src/fastdds/include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp:26, 
from /home/runner/work/Fast-DDS-docs/Fast-DDS-docs/src/fastdds/src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp:15: 
In member function ‘void eprosima::fastcdr::optional<T>::reset(bool) [with T = eprosima::fastdds::dds::xtypes::CompleteTypeDetail]’, 
inlined from ‘eprosima::fastcdr::optional<T>& eprosima::fastcdr::optional<T>::operator=(const eprosima::fastcdr::optional<T>&) [with T = eprosima::fastdds::dds::xtypes::CompleteTypeDetail]’ at …
```

[21623] Fix compilation warning in Ubuntu 24.04 with `-Werror`

---

.github/workflows/reusable-ubuntu-ci.yml

This PR introduces a new step in CI that generates the types defined in `dds-type-tests` with `-python` arg for checking failures.
Susccessfull generation (after the fix in #294): [here](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/10722426227/attempts/1)
Failing run (before the fix in the previous PR): [here](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/10880963120/job/30188905974)
*Note: we may add backports* 
@Mergifyio backport 3.3.x 2.5.x 2.1.x
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation.

[21592] Test generation of types with `-python` in ci

---

src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

Currently a collection of TK_UINT8 and a collection of TK_BYTE will be registered by the same typename. But are different types. This PR fixes it.
Depends on:
- eprosima/idl-parser#160
- eprosima/fast-dds#5251
- See eprosima/fast-dds#5251

[21686] Use different typename for collections of TK_UINT8 and TK_BYTE

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

This PR adds support for settting a value to an enumeration literal. For example:
```omg-idl
enum MyEnum
{
@value(-3)
ENUM_VALUE1,
@value(0)
ENUM_VALUE2
};
```
Depends on:
- eprosima/dds-types-test#36
- eprosima/fast-dds#5109
- eprosima/fast-dds-docs#917

[21380] Support setting value to an enumeration literal using annotation @value

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg

Currently the equality operator might return `false` when comparing a union initialized with its implicit default value and the same generated by another middleware. This is because we expects the discriminator's value should be equal, but it is not mandatory. This PR fixes this.

[21788] Improve equality operator for unions

---

src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

Structs are currently registered in the type object registry with their scoped name, instead of using their ROS 2 scoped name when `typeros2` is provided. As a consequence, there is a discrepancy between the name with which the type is registered in the type object registry and the name embedded in the generated TypeSupport.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.

[21758] Fix structs TypeObject registration with -typeros2 option

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubMain.stg

When a union uses an alias with scope, the generated source code fails compiling. This PR fixes it.
Depends on:
- eprosima/dds-types-test#39
- eprosima/idl-parser#164

[21825] Fix generated code compilation when a union uses an alias with scope

---

src/main/java/com/eprosima/fastdds/idl/templates/eprosima.stg

This PR fixes a corner case with sequences of alias of primitives inside modules. The generated code doesn't compile due to how the type name is generated.
```omg-idl
module Common_Module
{
typedef char My_Char;
typedef sequence<My_Char, 20> My_String;
};
module NoCommon_Module
{
typedef Common_Module::My_String My_AliasString;
typedef sequence<My_AliasString> My_SequenceString;
struct My_Structure
{
My_SequenceString list;
};
};
```
Depends on:
- eprosima/dds-types-test#40

[21980] Fix sequence of alias of primitives inside modules

---

src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg

According with new `fastcdr`  API usage, the generated code should call `Cdr::set_dds_cdr_options()`.
Depends on:
- eprosima/fast-cdr#244
@Mergifyio backport 3.3.x
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation.

[22043] Call Cdr::set_dds_cdr_options() when TypeSupport encodes

---

src/main/java/com/eprosima/fastdds/fastddsgen.java

Added a function that checks if the paths included with the -I function have already been added, and skips them if so. This solves issue #78, and was suggested by the original author. I had to update a couple of terms to the new notation, so we should be careful with backports.
@Mergifyio backport 3.3.x 2.5.x 2.1.x
Fixes #78
-  _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.

[13740] Add afunction that checks for repeated -I paths (issue #78)

---

src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg

This PR updates the generated CMakeLists.txt code to include the `CMAKE_BUILD_TYPE` configuration as `Release` by default.

[21725] Update example CMakeList to force default CMAKE_BUILD_TYPE

---

.github/pull_request_template.md
.github/workflows/mirror.yml
build.gradle

This PR bumps version to 4.1.0, and changes mirror and PR template for 4.1.x
- _N/A: New feature has been documented/Current behavior is correctly described in the documentation. 

[22815] Branch out 4.1.x

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg

This PR introduces the following improvements on the code generated for SWIG interfaces:
1. A setter for `fixed_string` members receiving a standard string is added.
2. A `%template` for each fixed_string member is generated.
This allows setting bounded string members with either of the following alternatives:
1. `struct_name.member_name("string value")`
2. ```
fixed_str = fixed_string_16("string value")
struct_name.member_name(fixed_str)
```
@Mergifyio backport 4.0.x
- See https://github.com/eProsima/Fast-DDS-python/pull/209 for the added tests 

[22850] Fix python code generation for bounded strings

---

.github/workflows/reusable-ubuntu-ci.yml
.github/workflows/ubuntu-ci.yml

This avoids failing CI on external contribution PRs.
Follows the same approach as in https://github.com/eProsima/Fast-DDS/pull/5220
@Mergifyio backport 4.0.x 3.3.x 2.5.x 2.1.x

[22858] Don't add `ci-pending` on external contribution PRs

---

src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

Changed in applied_verbatim_annotation the type_ann_builtin_$annotation_name$ -> type_ann_builtin_$name$ to fix the following error when not using `-no-typeobjectsupport` option:
`ERROR: context [/struct_type /complete_type_detail /type_annotations /_sub45 /applied_verbatim_annotation] 14:18 attribute annotation_name isn't defined`
e.g. for ros2 Header.idl file
Discussion: https://github.com/eProsima/Fast-DDS-Gen/discussions/406
@Mergifyio backport 4.0.x
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally

Fix typo in XTypesTypeObjectSource.stg

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
src/main/java/com/eprosima/fastdds/idl/grammar/Interface.java
src/main/java/com/eprosima/fastdds/idl/grammar/Operation.java

This PR adds the necessary changes for Fast DDS Gen to generate code in the header files for interface constructs.
From the following `calculator.idl` file:
<details>
```
module calculator_example
{
// This exception will be thrown when an operation result cannot be represented in a long
exception OverflowException
{
};
// For the filter operation
enum FilterKind
{
EVEN,  // return even numbers
ODD,   // return odd numbers
PRIME  // return prime numbers
};
interface Calculator
{
// Returns the minimum and maximum representable values
void representation_limits(out long min_value, out long max_value);
// Returns the result of value1 + value2
long addition(in long value1, in long value2) raises (OverflowException);
// Returns the result of value1 + value2
long subtraction(in long value1, in …
```

[22909] Generate code for interfaces in header files

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
src/main/java/com/eprosima/fastdds/idl/templates/InterfaceDetails.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeader.stg

This PR generates the request and reply data structures for an interface in the `<idl_name>_details.hpp`
From the following `calculator.idl` file:
<details>
```
module calculator_example
{
// This exception will be thrown when an operation result cannot be represented in a long
exception OverflowException
{
};
// For the filter operation
enum FilterKind
{
EVEN,  // return even numbers
ODD,   // return odd numbers
PRIME  // return positive prime numbers
};
interface Calculator
{
// Returns the minimum and maximum representable values
void representation_limits(out long min_value, out long max_value);
// Returns the result of value1 + value2
long addition(in long value1, in long value2) raises (OverflowException);
// Returns the result of value1 + value2
long subtraction(in long value1, in …
```

[22917] Generate request / reply data structures

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
src/main/java/com/eprosima/fastdds/idl/grammar/Exception.java
src/main/java/com/eprosima/fastdds/idl/grammar/Interface.java
src/main/java/com/eprosima/fastdds/idl/grammar/Operation.java
src/main/java/com/eprosima/fastdds/idl/grammar/Param.java
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg

This PR adds ServiceTypeSupport code generation for interfaces:
- __NO__: New feature has been documented/Current behavior is correctly described in the documentation. 
- Will do a final documentation PR for the whole feature

[22996] Generate ServiceTypeSupport for interfaces

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Interface.java
src/main/java/com/eprosima/fastdds/idl/templates/ClientHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/ClientSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/InterfaceDetails.stg

This generates the code for a client to consume an interface.
Depends on:
* https://github.com/eProsima/Fast-DDS/pull/5760
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- Will add tests when we also have the service code generation
- __NO__: New feature has been documented/Current behavior is correctly described in the documentation. 
- Will do a final documentation PR for the whole feature

[23017] Generate code for interface clients

---

src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg
src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg
src/main/java/com/eprosima/fastdds/solution/Project.java

Fixes a bug in Windows when generating `CMakeLists.txt`
@Mergifyio backport 4.0.x 3.3.x 2.5.x 2.1.x (not sure if all, only those supporting relative dir generation)
- Affects only Windows, where we currently have no CI

[23094] Escape folder separator in generated `CMakeLists.txt`

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Operation.java
src/main/java/com/eprosima/fastdds/idl/templates/ClientHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/ClientSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerImplementation.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerSource.stg

This generates the code for a server to provide an interface.
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- Will add tests when doing the final PR from the intermediate branch
- __NO__: New feature has been documented/Current behavior is correctly described in the documentation. 
- Will do a final documentation PR for the whole feature

[23069] Generate code for interface servers

---

src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg

This PR adds the scope (if present) to certain type values.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports have been included in the description.

[23151] Fix scope in TypeObjectSource.stg

---

src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
src/main/java/com/eprosima/fastdds/fastddsgen.java
src/main/java/com/eprosima/fastdds/idl/grammar/Annotation.java
src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
src/main/java/com/eprosima/fastdds/idl/grammar/Exception.java
src/main/java/com/eprosima/fastdds/idl/grammar/Interface.java
src/main/java/com/eprosima/fastdds/idl/grammar/Operation.java
src/main/java/com/eprosima/fastdds/idl/grammar/Param.java
src/main/java/com/eprosima/fastdds/idl/templates/ClientHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/ClientSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/InterfaceDetails.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerImplementation.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg

This PR adds C++ code generation for IDL interfaces (a.k.a RPC).
* The generated client interface provides an asynchronous API based on `std::future`.
* The generated server interface allows for aggregating the operation implementation (thus decoupling the DDS logic from the operation logic)
* Includes support for custom extension `@feed`.
This PR depends on the following ones and must be merged after them:
* https://github.com/eProsima/Fast-DDS/pull/5801
* https://github.com/eProsima/IDL-Parser/pull/172
* https://github.com/eProsima/IDL-Parser/pull/176
* https://github.com/eProsima/dds-types-test/pull/43
- https://github.com/eProsima/dds-types-test/pull/43
- Related documentation PR: eProsima/Fast-DDS-docs#1064

[23153] Generate code for interfaces and support `@nested`

---

src/main/java/com/eprosima/fastdds/fastddsgen.java

This PR adds the required logic to apply user templates to included IDL files.
If the `output file name` specified in `-extrastg` contains the character '@', the custom template will be also applied to included IDL files. The '$' will be replaced with the included file name. 
Usage example:
`-extrastg /path/to/template/Custom.stg @MyCustomTemplate.cpp`
Above command will generate file: `HelloWorldMyCustomTemplate.cpp` in case `HelloWorld.idl` was included.
@Mergifyio backport 4.0.x 3.3.x 2.5.x
- Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/1066

[23150] Apply user template to included IDL files

---

src/main/java/com/eprosima/fastdds/fastddsgen.java

This PR is backport of #472: 
This PR adds the required logic to apply user templates to included IDL files.
If the output file name specified in -extrastg contains the character '@', the custom template will be also applied to included IDL files. The '@' will be replaced with the included file name.
Usage example:
-extrastg /path/to/template/Custom.stg @MyCustomTemplate.cpp
Above command will generate file: HelloWorldMyCustomTemplate.cpp in case HelloWorld.idl was included.
@Mergifyio backport 3.3.x 2.5.x

[23150] Apply user template to included IDL files (backport #472)

---

src/main/java/com/eprosima/fastdds/idl/templates/ServerHeader.stg
src/main/java/com/eprosima/fastdds/idl/templates/ServerSource.stg

This adds a `ServerSchedulingStrategy` interface for each generated RPC server, allowing the user to create a server with a custom scheduling of requests, instead of always using a thread pool.
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- Tests for interfaces will be added in a follow-up

[23271] Allow injection of execution scheduling to RPC servers

---

src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg

This PR introduces a Python string getter for fixed string members.
The generated getter follows the naming convention:
- <member_name>_str
This provides direct access to the member value as a Python str.
-  N/A New feature has been documented/Current behavior is correctly described in the documentation. 

[23675] Add python-string getter from fixed string

---

.github/pull_request_template.md
.github/workflows/nightly-ubuntu-ci.yml

This PR does the following:
- Removes 4.0.x backport
- Removes 2.5.x backport
- Adds a new nightly for Fast DDS 3.2.x using Fast DDS Gen 4.1.x.
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 

[23657] Remove EOL versions & add new nightly for Fast DDS 3.2.x with 4.1.x

---

build.gradle

It does not make sense to install something that has not been built 😉 
@Mergifyio backport 3.3.x 2.1.x

[23731] Make install task depend on assemble task

---

.github/workflows/reusable-ubuntu-ci.yml
src/main/java/com/eprosima/fastdds/idl/grammar/Interface.java
src/main/java/com/eprosima/fastdds/idl/grammar/Operation.java

Support for `@feed` will be part of Fast DDS Pro.
Depends on:
* https://github.com/eProsima/dds-types-test/pull/47
* https://github.com/eProsima/Fast-DDS/pull/6052
* https://github.com/eProsima/Fast-DDS-python/pull/256
- Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/1135

[23702] Remove support for `@feed` annotations

---

.github/workflows/reusable-ubuntu-ci.yml

Since Fast DDS python requires CMake version 3.24, we need to update the CI here accordingly.

[23747] Update CMake version in CI

---

src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg

Avoid using a get_python_lib deprecated function

[23755] Avoid using a get_python_lib deprecated function
