eProsima/Fast-DDS-Gen

- build.gradle
This PR solves the versioning problem explained in #4 
It also updates IDL-Parser to fix the testing deadlock.
> Bugfix/versioning [6492]

- build.gradle
> Fixing version file generation. [6552]

- src/main/java/com/eprosima/fastrtps/idl/templates/Common.stg
> Fixed getKeyMaxCdrSerializedSize on inherited data

- build.gradle
- colcon.pkg
- scripts/fastrtpsgen
- scripts/fastrtpsgen.bat
- scripts/fastrtpsgen.in
- src/test/java/com/eprosima/fastrtps/FastRTPSGenTest.java
With this PR `fastrtpsgen` could be build with `colcon`.
> Support colcon

- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
> Zero size collection fix

- gradle/wrapper/gradle-wrapper.properties
Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>
>  Gradlew version upped to 6.4 [9852]

- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/Common.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubMain.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
Related to eProsima/Fast-DDS#1591
Makes use of https://github.com/eProsima/IDL-Parser/pull/40 to implement `is_plain` and `is_bounded` methods.
> Support for new extensions to TopicDataType [9051]

- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/JNISource.stg
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
> Account for submessage alignment

- build.gradle
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
> Bump version to v2.1.1

- src/main/java/com/eprosima/fastdds/fastddsgen.java
- src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg
Improve installation for target files.
> Improve CMakeLists.txt for swig bindings [13490]

- build.gradle
#95 Updated the IDL Parser submodule, but the build dependency was not updated
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
> Update IDL Parser build dependency

- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg
This PR adds necessary changes for SWIG generated files for support on Windows.
> Fix swig for windows [14076]

- build.gradle
- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
> Fix code generation for maps [14710]

- build.gradle
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
> [15600] Upgrade IDL-Parser submodule to v1.4.0

- build.gradle
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
> [15600] Bump version to v2.2.0

- build.gradle
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
> [16440] Bump version to v2.3.0

- build.gradle
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/StructTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/templates/Common.stg
> [17286] Bump version to v2.4.0 and update IDL parser submodule to v1.5.0

- src/main/java/com/eprosima/fastdds/idl/parser/typecode/ArrayTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
Depends on:
- eProsima/IDL-Parser#69
> Fix calculation of max serialized size for multi-dimensional arrays [18190]

- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
> [18631] Capture all fastcdr exceptions on generated PubSubType

- src/main/java/com/eprosima/fastcdr/idl/templates/TypeObjectSource.stg
to address https://github.com/eProsima/Fast-DDS-Gen/issues/184
> call register message type once

- src/main/java/com/eprosima/fastdds/fastddsgen.java
Extra option added to provide a template run time. Custom user code could be generated from idl files without recompiling the generator itself.
> [13762] Add custom stg templates as an option

- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
- src/main/java/com/eprosima/fastdds/fastddsgen.java
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSwigInterface.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg
- src/main/java/com/eprosima/fastdds/solution/Project.java
This PR has been tested with the following PR which implements some tests for python modules. 
- https://github.com/eProsima/Fast-DDS-python/pull/54
> Python modules support

- .gitmodules
- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/eprosima.stg
- src/test/java/com/eprosima/fastdds/FastDDSGenTest.java
Changes neccesary to make Fast-DDS-Gen work with all the IDLs from dds-types-test repo.
Depends on:
- https://github.com/eProsima/Fast-DDS/pull/3623
- https://github.com/eProsima/IDL-Parser/pull/77
- https://github.com/eProsima/dds-types-test/pull/1
> Changes neccesary to make Fast-DDS-Gen work with all the IDLs from dds-types-test repo [19113]

- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
Depends on:
- eprosima/idl-parser#87
> [19453] Fix bitmask initial value

- build.gradle
This PR:
* Bumps version to v3.0.0
* Updates submodules: IDL Parser & DDS Types Test
> [19453] Prepare for Fast DDS-Gen v3.0.0

- src/main/java/com/eprosima/fastdds/idl/parser/typecode/ArrayTypeCode.java
Depends on:
- eprosima/idl-parser#91
> Move code to idl-parser

- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
[Regression](https://github.com/eProsima/dds-types-test/pull/9).
* eProsima/IDL-Parser#96
> [19680] Enable `-Wall`, fix build warnings and fix regression

- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/ArrayTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/MapTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/SequenceTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/SetTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/StringTypeCode.java
Depends on:
- eprosima/idl-parser#94
> Fixed usage of const as literals

- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg
Depends on:
- eprosima/fast-cdr#169
> Support of optional members in python [19675]

- resources/Custom.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/JavaType.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubMain.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSwigInterface.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/JNIHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/JNISource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/JavaSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
This PR:
* Updates IDL Parser submodule
* Updates templates to call the new defined collection templates
> [19672] Collection templates

- .github/actions/fetch-fastddsgen-repos/action.yml
- .github/workflows/ci.yaml
- src/main/java/com/eprosima/fastdds/fastddsgen.java
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg
Depends on:
- eprosima/idl-parser#98
> Improve CI [19790]

- .github/workflows/ci.yaml
- src/main/java/com/eprosima/fastcdr/idl/context/Context.java
- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeaderv1.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSourcev1.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
- src/main/java/com/eprosima/fastcdr/idl/util/CdrVersion.java
- src/main/java/com/eprosima/fastdds/fastddsgen.java
- src/main/java/com/eprosima/fastdds/idl/grammar/Context.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/PrimitiveTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/StringTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/templates/CMakeLists.stg
- src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/SwigCMake.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg
- src/test/java/com/eprosima/fastdds/FastDDSGenTest.java
Depends on:
- eprosima/dds-types-test#14
- eprosima/idl-parser#102
> Coexist fastcdr v1 and v2 [new approach] [19874]

- build.gradle
This PR:
* Bumps the project version to 3.1.0
* Updates IDL parse submodule to v2.0.0
> [19898] Bump version to 3.1.0

- src/main/java/com/eprosima/fastcdr/idl/templates/JavaType.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeaderv1.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSource.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesSourcev1.stg
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/UnionTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectSource.stg
This PR only updates the IDL Parser submodule to pass the CI of:
* eProsima/IDL-Parser#106
> [19932] Update IDL parser submodule to support new Union discriminator as a Member

- src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
> [20052] Fix tests for common struct name in different modules

- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
- src/main/java/com/eprosima/fastdds/fastddsgen.java
Depends on:
- eprosima/idl-parser#112
> Support for C++ enum class [20065]

- src/main/java/com/eprosima/fastdds/idl/parser/typecode/MemberedTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/parser/typecode/StructTypeCode.java
- src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
* eProsima/dds-types-test#17
* eProsima/IDL-Parser#115
> Support for annotations to set MemberId [20114]

- build.gradle
> [20129] Bump to version v3.2.0

- .github/workflows/mirror.yml
> [20055] Set mirror to 2.3.x

- src/main/java/com/eprosima/fastdds/idl/templates/XTypesTypeObjectSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/eprosima.stg
Correctly use the bounded IDL Parser API.
> [20335] Fix bounded collections with unbounded elements

- .github/workflows/mirror.yml
This pr updates mirror workflow to 3.3.x
> [20495] Set mirror to 3.3.x

- src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg
- src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypesCdrAuxHeaderImpl.stg
Depends on:
- eprosima/dds-types-test#29
- eprosima/idl-parser#124
> New implementation for unions [20588]

- src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
- src/main/java/com/eprosima/fastdds/idl/templates/TypeObjectTestingTestSource.stg
eProsima/Fast-DDS#4368 modifies TypeObjectPair API. This PR updates the TypeObjectSupport tests template accordingly.
> [20335] Fix TypeObjectPair API

- src/main/java/com/eprosima/fastdds/fastddsgen.java
This PR introduces improvements regarding path processing: in particular path normalization
Related idl parser PR: https://github.com/eProsima/IDL-Parser/pull/131
Fixes: #328
> [20755] Improve path processing

- .github/fastddsgen.meta
- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/ubuntu-ci.yaml
- README.md
This PR prepares the 4.0.x-devel branch to become Fast DDS Gen master.
> [20893] Prepare 3.0.x-devel to become master

- src/main/java/com/eprosima/fastdds/fastddsgen.java
This PR introduces improvements regarding path processing: in particular path normalization
Related idl-parser https://github.com/eProsima/IDL-Parser/tree/3.0.x
> [20755] Improve path processing 

- .github/workflows/reusable-ubuntu-ci.yaml
- .github/workflows/ubuntu-ci.yaml
This PR updates of other products versions in the GitHub workflow to the last compatible ones
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports have been included in the description.
> [21029] Update GitHub workflow

- .github/pull_request_template.md
- .github/workflows/nightly-ubuntu-ci.yml
- RELEASE_SUPPORT.md
This PR sets 2.1.x (associated to Fast DDS 2.13.x) as EOL
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI results: failing tests are unrelated with the changes.
> [21310] Set 3.2.x (Fast DDS 2.13.x) as EOL

- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/weekly-ubuntu-ci.yml
Thi nighly job had a typo that make it not work. This PR fixes the typo
> [21226] Fix nightly job

- build.gradle
This PR bumps the Fast DDS-Gen version to v4.0.1, and updates the IDL-Parser submodule with its latest release v4.0.1
> [21636] Bump version to v4.0.1 and update IDL-Parser submodule

- build.gradle
This PR  bumps de Fast DDS Gen version to v4.0.2 and updates the IDL parser submodule with that new version v4.0.2
- **NA** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- **NA** New feature has been documented/Current behavior is correctly described in the documentation. 
- **NA** Applicable backports have been included in the description.
> [21783] Bump version to v4.0.2

- build.gradle
Merge after:
- https://github.com/eProsima/Fast-DDS-statistics-backend/pull/256
- https://github.com/eProsima/Fast-DDS-python/pull/198
- https://github.com/eProsima/ShapesDemo/pull/190
- https://github.com/eProsima/Fast-DDS-docs/pull/965
- https://github.com/eProsima/Fast-DDS/pull/5427
- https://github.com/eProsima/Discovery-Server/pull/110
> [21560] Bump to v3.3.1

- build.gradle
Merge after updating other repos:
**3.1.x:**
- https://github.com/eProsima/Fast-DDS/pull/5502
- https://github.com/eProsima/Fast-DDS-docs/pull/991
- https://github.com/eProsima/ShapesDemo/pull/192
- Discovery Server: _N/A_
- Statistics backend: _N/A_
- Fast DDS python: _N/A_
**master:**
- https://github.com/eProsima/Fast-DDS/pull/5503
- https://github.com/eProsima/Fast-DDS-docs/pull/992
- https://github.com/eProsima/ShapesDemo/pull/193
- https://github.com/eProsima/Discovery-Server/pull/111
- https://github.com/eProsima/Fast-DDS-statistics-backend/pull/261
- https://github.com/eProsima/Fast-DDS-python/pull/202
- _N/A_: New feature …
> [22497] Bump version to v4.0.3

- build.gradle
Merge after updating the following repos:
**3.1.x**
* https://github.com/eProsima/Fast-DDS/pull/5721
* Fast DDS docs N/A
* Discovery Server N/A
* ShapesDemo N/A
* Statistics Backend N/A
* https://github.com/eProsima/Fast-DDS-python/pull/217
**master**
* https://github.com/eProsima/Fast-DDS/pull/5720
* Fast DDS docs N/A
* Discovery Server N/A
* ShapesDemo N/A
* https://github.com/eProsima/Fast-DDS-statistics-backend/pull/269
* https://github.com/eProsima/Fast-DDS-python/pull/216
- **N/A** Applicable backports have been included …
> [22858] Bump version to v4.0.4

- RELEASE_SUPPORT.md
This PR updates the RELEASE_SUPPORT.md file to update versioning of Fast DDS Gen with latest releases of Fast DDS.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports have been included in the description.
- _N/A_: Check CI results: changes do not issue any warning.
- _N/A_: Check CI results: failing tests are unrelated with the changes.
> [21427] Add 3.2 & EOL versions to Release Support

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/nightly-ubuntu-ci.yml
- build.gradle
This PR bumps version to 4.2.0, and changes mirror and PR template for 4.2.x
> [23520] Branch out 4.2.x

- .github/workflows/reusable-ubuntu-ci.yml
- src/main/java/com/eprosima/fastdds/fastddsgen.java
Backport from #491 
- N/A Commit messages follow the project guidelines. 
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
> [23657] Fix typedef-only IDL (#491) 
